Repository oostaoo-consulting/smart-scrapper, pull requests merged in 2023-06, with the labels that each got.

#50 #49 : Adding users listing
  src/components/1atoms/SocialIcon/SocialIcon.tsx
  src/components/2molecules/Card/Card.tsx
  src/components/3organisms/CardsSide/CardsSide.tsx
  src/pages/index.tsx
  types/Person.d.ts
Labels: enhancement, draft

#56 #55 : implement a users filter to graphQL API
  src/contexts/profilesContext.tsx
  src/graphql/dataSources/githubAPI.ts
  src/graphql/resolvers.test.ts
  src/graphql/typeDefs.ts
  types/GithubAPIReturned.d.ts
Labels: enhancement

#52 #51 : Tests for Search Saved
  src/components/2molecules/SearchBar/SearchBar-context.test.tsx
  src/components/2molecules/SearchBar/SearchBar.test.tsx
  src/components/2molecules/SearchSaved/SearchSaved.tsx
  src/components/2molecules/SearchSaved/searchSaved.test.tsx
  src/components/3organisms/SearchesSaved/SearchesSaved.tsx
  src/components/3organisms/SearchesSaved/searchesSaved.test.tsx
  src/pages/index.tsx
  src/utils/localStorage.tsx
Labels: enhancement

#65 #62 & #63 : fix scroll to up and first page after each new datas
  src/pages/index.tsx
Labels: bug

#67 #60 : UpdateDetailCard
  .husky/pre-commit
  src/components/2molecules/Card/Card.tsx
  src/components/3organisms/Favorites/Favorites.tsx
  src/graphql/resolvers.test.ts
  src/pages/index.tsx
  src/utils/localStorage.tsx
Labels: enhancement

#76 #69: Fix error pagination user
  src/components/2molecules/Card/Card.tsx
  src/pages/index.tsx
Labels: enhancement, draft

#81 #74 & #79 : Fix Inputs
  src/components/1atoms/MainButton/MainButton.tsx
  src/components/2molecules/Card/Card.tsx
  src/components/2molecules/SearchBar/SearchBar.tsx
  src/components/3organisms/Search/Search.tsx
  src/pages/index.tsx
Labels: bug

#82 Link datas in Popup card
  src/components/2molecules/Card/Card.tsx
  src/components/2molecules/CardDetails/CardDetails.tsx
  src/contexts/dataContext.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: enhancement

#83 Feature/#72/Redux
  README.md
  package.json
  src/components/2molecules/Card/Card.tsx
  src/components/2molecules/Pagination/Pagination.tsx
  src/components/3organisms/CardsSide/CardsSide.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/redux/features/data-slice.ts
  src/redux/provider.tsx
  src/redux/store.ts
  yarn.lock
Labels: enhancement, draft
