Repository oostaoo-consulting/smart-scrapper, pull requests merged in 2023-05, with the labels that each got.

#29 enhance Layout with tabs and switch two parts in desktop
  ___tests___/Home.test.tsx
  src/components/1atoms/Button/Button.tsx
  src/components/1atoms/Button/button.test.tsx
  src/components/1atoms/SearchButton/SearchButton.tsx
  src/components/2molecules/Card/Card.tsx
  src/components/2molecules/Card/card.test.tsx
  src/components/2molecules/NavBar/NavBar.tsx
  src/components/2molecules/NavBar/navbar.test.tsx
  src/components/2molecules/SearchBar/SearchBar.tsx
  src/components/2molecules/SearchSaved/SearchSaved.tsx
  src/components/2molecules/SearchSaved/searchSaved.test.tsx
  src/components/3organisms/Favorites/Favorites.test.tsx
  src/components/3organisms/Favorites/Favorites.tsx
  src/components/3organisms/SearchesSaved/SearchesSaved.tsx
  src/components/3organisms/SearchesSaved/searchesSaved.test.tsx
  src/pages/index.tsx
  src/tests/Home.test.tsx
Labels: enhancement

#30 #22 : Mise en place API, communication avec ChatGPT
  .eslintrc.json
  README.md
  package.json
  src/pages/api/openai/index.ts
  yarn.lock
Labels: documentation, enhancement, ready to review

#33 #12 : favorite part
  src/pages/index.tsx
  src/tests/Home.test.tsx
Labels: bug, ready to review

#38 #26 Développer la pagination du site
  jest.config.js
  package.json
  src/components/1atoms/Button/Button.tsx
  src/components/2molecules/NavBar/NavBar.tsx
  src/components/2molecules/Pagination/Pagination.tsx
  src/components/3organisms/CardsSide/CardsSide.tsx
  src/pages/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: ready to review

#36 #23 : fetch api from input
  .env.example
  .eslintrc.json
  src/components/1atoms/Button/Button.tsx
  src/components/1atoms/Button/button.test.tsx
  src/components/1atoms/Input/Input.tsx
  src/components/1atoms/Input/input.test.tsx
  src/components/2molecules/NavBar/NavBar.tsx
  src/components/2molecules/SearchBar/SearchBar.test.tsx
  src/components/2molecules/SearchBar/SearchBar.tsx
  src/components/3organisms/CardsSide/CardsSide.tsx
  src/contexts/profilesContext.tsx
  src/graphql/resolvers.ts
  src/pages/_app.tsx
  types/GithubAPIReturned.d.ts
Labels: enhancement, draft

#39 #32 : Ajout de règles ESLint pour typescript
  .eslintrc.json
  src/components/1atoms/Button/Button.tsx
  src/components/1atoms/Button/button.test.tsx
  src/components/1atoms/Input/Input.tsx
  src/components/1atoms/Input/input.test.tsx
  src/components/1atoms/MainButton/MainButton.tsx
  src/components/1atoms/MainButton/mainButton.test.tsx
  src/components/1atoms/Paragraph/Paragraph.tsx
  src/components/1atoms/Paragraph/paragraph.test.tsx
  src/components/1atoms/Title/Title.tsx
  src/components/1atoms/Title/title.test.tsx
  src/components/2molecules/Card/Card.tsx
  src/components/2molecules/CardDetails/CardDetails.tsx
  src/components/2molecules/NavBar/NavBar.tsx
  src/components/2molecules/Pagination/Pagination.tsx
  src/components/2molecules/SearchBar/SearchBar.tsx
  src/components/2molecules/SearchSaved/SearchSaved.tsx
  src/components/3organisms/CardsSide/CardsSide.tsx
  src/components/3organisms/Favorites/Favorites.tsx
  src/components/3organisms/Header/Header.tsx
  src/components/3organisms/Search/Search.tsx
  src/components/3organisms/SearchesSaved/SearchesSaved.tsx
  src/components/Container/Container.tsx
  src/contexts/profilesContext.tsx
  src/graphql/resolvers.test.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: documentation, enhancement, ready to review

#41 #40 : update-tests
  package.json
  src/components/1atoms/Button/button.test.tsx
  src/components/2molecules/Card/Card.tsx
  src/components/2molecules/Card/card.test.tsx
  src/components/2molecules/CardDetails/CardDetails.tsx
  src/components/2molecules/CardDetails/cardDetails.test.tsx
  src/components/2molecules/Pagination/pagination.test.tsx
  src/components/2molecules/SearchBar/SearchBar-context.test.tsx
  src/components/3organisms/CardsSide/CardsSide.tsx
  src/contexts/profilesContext.test.tsx
  src/contexts/profilesContext.tsx
  src/pages/index.tsx
  src/tests/Home-mediaquery.test.tsx
  yarn.lock
Labels: enhancement, draft

#42 #24 : Development view card
  jest.config.js
  src/components/2molecules/Card/Card.tsx
  src/components/2molecules/Card/card.test.tsx
  src/components/2molecules/CardDetails/CardDetails.tsx
  src/components/2molecules/Pagination/Pagination.tsx
  src/components/2molecules/Pagination/pagination.test.tsx
  src/components/2molecules/SearchBar/SearchBar.tsx
  src/components/3organisms/CardsSide/CardsSide.tsx
  src/pages/index.tsx
  src/tests/Home.test.tsx
Labels: enhancement, draft
